In [38]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [40]:
df=pd.read_csv('movie_collection.csv')
df.head(20)

Collection  Marketing expense  Production expense  Multiplex coverage  \
0        48000            20.1264               59.62               0.462   
1        43200            20.5462               69.14               0.531   
2        69400            20.5458               69.14               0.531   
3        66800            20.6474               59.36               0.542   
4        72400            21.3810               59.36               0.542   
5        57400            20.5970               59.36               0.542   
6        45800            21.7658               70.74               0.476   
7        44200            22.8910               70.74               0.476   
8        33000            24.2248               70.74               0.476   
9        37800            23.4008               70.74               0.476   
10       30000            24.4978               70.74               0.476   
11       37800            22.3494               70.74               0.476   
12       43400            21.8756               70.74               0.476   
13       40800            32.5952               71.28               0.462   
14       36400            32.7592               71.28               0.462   
15       39800            32.5478               71.28               0.462   
16       46200            41.0786               71.28               0.462   
17       35000            35.6840               71.28               0.462   
18       40400            36.0542               71.28               0.462   
19       36400            34.5160               71.28               0.462   

       Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0   36524.125         138.7               7.825                8.095   
1   35668.655         152.4               7.505                7.650   
2   39912.675         134.6               7.485                7.570   
3   38873.890         119.3               6.895                7.035   
4   39701.585         127.7               6.920                7.070   
5   35718.650         132.2               6.890                7.100   
6   33396.660         140.1               7.065                7.265   
7   34285.460         169.6               6.980                7.075   
8   31280.205         173.5               6.910                7.075   
9   33352.220         159.4               6.665                6.725   
10  35424.235         167.8               6.675                6.845   
11  33379.995         156.4               6.865                7.035   
12  32713.395         112.5               7.120                7.430   
13  33046.695         135.3               7.640                7.705   
14  33863.280         158.0               7.700                7.900   
15  32407.870         130.0               7.700                7.825   
16  32968.925         102.8               7.670                7.805   
17  33274.450         155.2               7.720                7.925   
18  30308.080         110.1               8.100                8.240   
19  31813.485         143.0               8.010                8.175   

    Director_rating  Producer_rating  Critic_rating  Trailer_views  \
0             7.910            7.995           7.94         527367   
1             7.440            7.470           7.44         494055   
2             7.495            7.515           7.44         547051   
3             6.920            7.020           8.26         516279   
4             6.815            7.070           8.26         531448   
5             6.885            7.005           7.26         498425   
6             7.150            7.400           8.96         459241   
7             6.875            7.170           7.96         400821   
8             6.850            7.000           7.96         295168   
9             6.575            6.855           7.96         412012   
10            6.725            7.060           8.96         369595   
11            6.745            6.

In [42]:
import statsmodels.api as sm
import statsmodels.api as sn
from sklearn.linear_model import LogisticRegression

In [44]:
df['Budget'].unique()

array([36524.125, 35668.655, 39912.675, 38873.89 , 39701.585, 35718.65 ,
       33396.66 , 34285.46 , 31280.205, 33352.22 , 35424.235, 33379.995,
       32713.395, 33046.695, 33863.28 , 32407.87 , 32968.925, 33274.45 ,
       30308.08 , 31813.485, 30941.35 , 33135.575, 34118.81 , 32291.215,
       32907.82 , 31102.445, 33591.085, 36079.725, 37074.07 , 31735.715,
       33729.96 , 33052.25 , 31669.055, 32957.815, 32446.755, 32496.75 ,
       33141.13 , 36635.225, 39018.32 , 37607.35 , 34268.795, 34502.105,
       33713.295, 31563.51 , 32141.23 , 33496.65 , 29991.445, 31119.11 ,
       33124.465, 33968.825, 36168.605, 33318.89 , 32707.84 , 40268.195,
       35457.565, 37862.88 , 34135.475, 32924.485, 31891.255, 35863.08 ,
       37562.91 , 39462.72 , 34940.95 , 32146.785, 32652.29 , 31074.67 ,
       32691.175, 35646.435, 33113.355, 33691.075, 34690.975, 34846.515,
       34918.73 , 34879.845, 34107.7  , 34618.76 , 32630.07 , 37368.485,
       36768.545, 35007.61 , 34257.685, 35490.895, 

In [46]:
df['Start_Tech_Oscar'].unique()

array([0, 1], dtype=int64)

In [48]:
z = df[['Budget']].values
y = df['Start_Tech_Oscar'].values

# Create and fit the logistic regression model
model = LogisticRegression()
model.fit(z, y)

LogisticRegression()

In [50]:
correlation = df['Budget'].corr(df['Start_Tech_Oscar'])

In [52]:
correlation 

0.027147653515770042

In [54]:
z_const=sn.add_constant(z)

In [56]:
z_const

array([[1.0000000e+00, 3.6524125e+04],
       [1.0000000e+00, 3.5668655e+04],
       [1.0000000e+00, 3.9912675e+04],
       ...,
       [1.0000000e+00, 3.8751680e+04],
       [1.0000000e+00, 3.7740670e+04],
       [1.0000000e+00, 3.3496650e+04]])

In [58]:
import statsmodels.discrete.discrete_model as sm

In [60]:
log = sm.Logit(y,z_const).fit()

Optimization terminated successfully.
         Current function value: 0.688641
         Iterations 4


In [62]:
log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Tue, 06 Aug 2024   Pseudo R-squ.:               0.0005348
Time:                        11:41:51   Log-Likelihood:                -348.45
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                    0.5414
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6707      0.805     -0.833      0.405      -2.249       0.908
x1          1.399e-05   2.29e-05      0.610      0.542   -3.09e-05    5.89e-05
==============================================================================
"""

In [64]:
df = pd.get_dummies(df)
df

Collection  Marketing expense  Production expense  Multiplex coverage  \
0         48000            20.1264               59.62               0.462   
1         43200            20.5462               69.14               0.531   
2         69400            20.5458               69.14               0.531   
3         66800            20.6474               59.36               0.542   
4         72400            21.3810               59.36               0.542   
..          ...                ...                 ...                 ...   
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0    36524.125         138.7               7.825                8.095   
1    35668.655         152.4               7.505                7.650   
2    39912.675         134.6               7.485                7.570   
3    38873.890         119.3               6.895                7.035   
4    39701.585         127.7               6.920                7.070   
..         ...           ...                 ...                  ...   
501  36624.115         142.6               8.680                8.775   
502  33996.600         150.2               8.780                8.945   
503  38751.680         164.5               8.830                8.970   
504  37740.670         162.8               8.730                8.845   
505  33496.650         154.3               8.640                8.880   

     Director_rating  Producer_rating  ...  Avg_age_actors  Num_multiplex  \
0              7.910            7.995  ...              23            494   
1              7.440            7.470  ...              42            462   
2              7.495            7.515  ...              38            458   
3              6.920            7.020  ...              45            472   
4              6.815            7.070  ...              55            395   
..               ...              ...  ...             ...            ...   
501            8.620            8.970  ...              27            561   
502            8.770            8.930  ...              20            600   
503            8.855            9.010  ...              31            576   
504            8.800            8.845  ...              47            607   
505            8.680            8.790  ...              45            604   

     Start_Tech_Oscar  3D_available_NO  3D_available_YES  Genre_Action  \
0                   0            False              True         False   
1                   1             True             False         False   
2                   0             True             False         False   
3                   0            False              True         False   
4                   0             True             False         False   
..                ...              ...               ...           ...   
501                 1             True             False          True   
502                 1            False              True          True   
503                 1             True             False         False   
504                 1            False              True         False   
505                 1            False              True         False   

     Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0           False        False            True                 True  
1           False         True           False                 True  
2            True        False           False                 True  
3           False         True           False                 True  
4           False         T

In [66]:
for col in df.columns:
    if df[col].dtype == bool:
        df[col] = df[col].astype(int)
print(df)

     Collection  Marketing expense  Production expense  Multiplex coverage  \
0         48000            20.1264               59.62               0.462   
1         43200            20.5462               69.14               0.531   
2         69400            20.5458               69.14               0.531   
3         66800            20.6474               59.36               0.542   
4         72400            21.3810               59.36               0.542   
..          ...                ...                 ...                 ...   
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_

In [68]:
df

Collection  Marketing expense  Production expense  Multiplex coverage  \
0         48000            20.1264               59.62               0.462   
1         43200            20.5462               69.14               0.531   
2         69400            20.5458               69.14               0.531   
3         66800            20.6474               59.36               0.542   
4         72400            21.3810               59.36               0.542   
..          ...                ...                 ...                 ...   
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0    36524.125         138.7               7.825                8.095   
1    35668.655         152.4               7.505                7.650   
2    39912.675         134.6               7.485                7.570   
3    38873.890         119.3               6.895                7.035   
4    39701.585         127.7               6.920                7.070   
..         ...           ...                 ...                  ...   
501  36624.115         142.6               8.680                8.775   
502  33996.600         150.2               8.780                8.945   
503  38751.680         164.5               8.830                8.970   
504  37740.670         162.8               8.730                8.845   
505  33496.650         154.3               8.640                8.880   

     Director_rating  Producer_rating  ...  Avg_age_actors  Num_multiplex  \
0              7.910            7.995  ...              23            494   
1              7.440            7.470  ...              42            462   
2              7.495            7.515  ...              38            458   
3              6.920            7.020  ...              45            472   
4              6.815            7.070  ...              55            395   
..               ...              ...  ...             ...            ...   
501            8.620            8.970  ...              27            561   
502            8.770            8.930  ...              20            600   
503            8.855            9.010  ...              31            576   
504            8.800            8.845  ...              47            607   
505            8.680            8.790  ...              45            604   

     Start_Tech_Oscar  3D_available_NO  3D_available_YES  Genre_Action  \
0                   0                0                 1             0   
1                   1                1                 0             0   
2                   0                1                 0             0   
3                   0                0                 1             0   
4                   0                1                 0             0   
..                ...              ...               ...           ...   
501                 1                1                 0             1   
502                 1                0                 1             1   
503                 1                1                 0             0   
504                 1                0                 1             0   
505                 1                0                 1             0   

     Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0               0            0               1                    1  
1               0            1               0                    1  
2               1            0               0                    1  
3               0            1               0                    1  
4               0          

In [84]:
from sklearn.impute import SimpleImputer
p = df.loc[:,df.columns != 'Start_Tech_Oscar']
k = df['Start_Tech_Oscar'].values
imputer = SimpleImputer(strategy='mean')
p = imputer.fit_transform(p)

In [86]:
model = LogisticRegression()
model.fit(p, k)

C:\Users\ANISHKA\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [90]:
correlation = df.corr()
cor = correlation['Start_Tech_Oscar']
cor

Collection            -0.154698
Marketing expense      0.013417
Production expense     0.024404
Multiplex coverage     0.004017
Budget                 0.027148
Movie_length          -0.016291
Lead_ Actor_Rating     0.035309
Lead_Actress_rating    0.040356
Director_rating        0.035768
Producer_rating        0.043612
Critic_rating          0.001084
Trailer_views          0.075783
Time_taken             0.064536
Twitter_hastags       -0.077333
Avg_age_actors        -0.040581
Num_multiplex          0.004857
Start_Tech_Oscar       1.000000
3D_available_NO        0.070371
3D_available_YES      -0.070371
Genre_Action          -0.003117
Genre_Comedy          -0.021134
Genre_Drama           -0.061414
Genre_Thriller         0.072842
MPAA_film_rating_PG         NaN
Name: Start_Tech_Oscar, dtype: float64

In [92]:
p_const = sn.add_constant(p)

In [94]:
p_const

array([[4.80000e+04, 2.01264e+01, 5.96200e+01, ..., 0.00000e+00,
        1.00000e+00, 1.00000e+00],
       [4.32000e+04, 2.05462e+01, 6.91400e+01, ..., 1.00000e+00,
        0.00000e+00, 1.00000e+00],
       [6.94000e+04, 2.05458e+01, 6.91400e+01, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [4.78000e+04, 2.12152e+01, 7.88600e+01, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [4.40000e+04, 2.21918e+01, 7.88600e+01, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [3.80000e+04, 2.09482e+01, 7.88600e+01, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00]])